import "dotenv/config"

const { GITHUB_WEBHOOK_KEY, GITHUB_APP_PRIVATE_KEY, GITHUB_APP_ID, GITHUB_APP_CLIENT_ID, GITHUB_APP_CLIENT_SECRET, GITHUB_APP_USER_ID } = process.env

if (!GITHUB_WEBHOOK_KEY || !GITHUB_APP_PRIVATE_KEY || !GITHUB_APP_ID || !GITHUB_APP_CLIENT_ID || !GITHUB_APP_CLIENT_SECRET || !GITHUB_APP_USER_ID) {
    throw new Error("Not enough env data: github")
}

const GithubAppConfig = {
    WEBHOOK_SECRET: GITHUB_WEBHOOK_KEY,
    PRIVATE_KEY: GITHUB_APP_PRIVATE_KEY,
    ID: GITHUB_APP_ID,
    CLIENT_ID: GITHUB_APP_CLIENT_ID,
    CLIENT_SECRET: GITHUB_APP_CLIENT_SECRET,
    USER_ID: GITHUB_APP_USER_ID
} as const

export default GithubAppConfig