import { APIApplicationCommandInteractionDataRoleOption, APIApplicationCommandInteractionDataStringOption, APIChatInputApplicationCommandInteraction, APIChatInputApplicationCommandInteractionData } from "discord-api-types/v10";

interface DiscordRegisterCommandInteractionData extends APIChatInputApplicationCommandInteractionData {
    options: [APIApplicationCommandInteractionDataStringOption, APIApplicationCommandInteractionDataRoleOption]
}

interface DiscordRegisterCommandInteraction extends APIChatInputApplicationCommandInteraction {
    data: DiscordRegisterCommandInteractionData
}

export default DiscordRegisterCommandInteraction